// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9xAFDI0_G0XPMeNxN_fp0OtqlHvB-Po',
    appId: '1:550930607837:android:f0973316f95f275e81b534',
    messagingSenderId: '550930607837',
    projectId: 'fyb-projects',
    databaseURL: 'https://fyb-projects.firebaseio.com',
    storageBucket: 'fyb-projects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXSlHHyz2hG7vTcwak2IXRL9lXozoBjs',
    appId: '1:550930607837:ios:e183f78fe374ac4f81b534',
    messagingSenderId: '550930607837',
    projectId: 'fyb-projects',
    databaseURL: 'https://fyb-projects.firebaseio.com',
    storageBucket: 'fyb-projects.firebasestorage.app',
    androidClientId: '550930607837-bb1cim4mgi71o53pe326ismiabbmpei7.apps.googleusercontent.com',
    iosBundleId: 'com.ars.ars',
  );
}
